
steps:
  - name: "gcr.io/cloud-builders/docker"
    id: "Build"
    args:
    - build
    - -t
    - gcr.io/${PROJECT_ID}/docs/prod/unreal-engine:latest
    - -t
    - gcr.io/${PROJECT_ID}/docs/prod/unreal-engine:$COMMIT_SHA
    - --file
    - documentation/Dockerfile
    - .

images:
  - gcr.io/${PROJECT_ID}/docs/prod/unreal-engine:$COMMIT_SHA
  - gcr.io/${PROJECT_ID}/docs/prod/unreal-engine:latest

timeout: 7200s
options:
  diskSizeGb: '200'
  machineType: E2_HIGHCPU_8
  #pool:
  #  name: 'projects/chris-pixo-sandbox-project/locations/us-central1/workerPools/build-pool'

