
steps:
  - name: "gcr.io/cloud-builders/docker"
    id: "Build"
    args:
    - build
    - -t
    - gcr.io/${PROJECT_ID}/${_APP_CODE}/${_LIFECYCLE}/${_SERVICE_NAME}:latest
    - -t
    - gcr.io/${PROJECT_ID}/${_APP_CODE}/${_LIFECYCLE}/${_SERVICE_NAME}:$COMMIT_SHA
    - --file
    - documentation/Dockerfile
    - .

images:
  - gcr.io/${PROJECT_ID}/${_APP_CODE}/${_LIFECYCLE}/${_SERVICE_NAME}:$COMMIT_SHA
  - gcr.io/${PROJECT_ID}/${_APP_CODE}/${_LIFECYCLE}/${_SERVICE_NAME}:latest

timeout: 7200s
options:
  diskSizeGb: '400'
  machineType: E2_HIGHCPU_8
