
steps:
  - name: "gcr.io/cloud-builders/docker"
    id: "Build"
    args:
    - build
    - -t
    - gcr.io/${PROJECT_ID}/docs/prod/${_DEST_REPO}:latest
    - -t
    - gcr.io/${PROJECT_ID}/docs/prod/${_DEST_REPO}:$COMMIT_SHA
    - --file
    - documentation/Dockerfile
    - .

images:
  - gcr.io/${PROJECT_ID}/docs/prod/${_DEST_REPO}:$COMMIT_SHA
  - gcr.io/${PROJECT_ID}/docs/prod/${_DEST_REPO}:latest

timeout: 7200s
options:
  diskSizeGb: '200'
  machineType: E2_HIGHCPU_8

substitutions:
  _DEST_REPO: ue4-apex

