
FROM	gcr.io/pixo-bootstrap/docs-docker-ue4-base as ue4

#build plugin cpp files

WORKDIR /generated

COPY	. .

#copy plugin into plugins folder
#UE4Editor-Cmd


#FROM	docs-docker-base
FROM	gcr.io/pixo-bootstrap/docs-docker-base:latest

ARG	CACHEBREAKER=https://www.random.org/cgi-bin/randbyte?nbytes=10&format=h

WORKDIR	/build

COPY	. .

#COPY	--from=ue4 

RUN	doxygen -v	# confirm doxygen version from docs-docker-base

# Force fresh git operations to avoid cached states
RUN	cd /build && \
	git clean -fd && \
	git submodule foreach --recursive 'git clean -fd' && \
	git submodule sync --recursive && \
	git submodule update --init --recursive --force && \
	cd documentation/docs-doxygen && \
	git fetch origin && \
	git reset --hard origin/main

ADD	$CACHEBREAKER skipcache22

RUN	./documentation/build.sh && \
	eval "$(cat ./documentation/env.sh | grep "PROJECT_URL")" && \
	mkdir -p /var/www/html/$PROJECT_URL && \
	cp -r ./documentation/html/* /var/www/html/$PROJECT_URL

#ENTRYPOINT ["/docker-entrypoint.sh"]
#CMD	["nginx", "-g", "daemon off;"]

