
FROM	gcr.io/pixo-bootstrap/docs-docker-ue4-base:latest as ue4

WORKDIR /project

# copy plugin into plugins folder
COPY	. /project/project/Plugins/plugin

RUN	ls -al /project/project/Plugins/

# build plugin cpp files
#RUN	UE4Editor-Cmd


#FROM	docs-docker-base
FROM	gcr.io/pixo-bootstrap/docs-docker-base:latest

ARG	CACHEBREAKER=https://www.random.org/cgi-bin/randbyte?nbytes=10&format=h

WORKDIR	/build

COPY	. .

#COPY	--from=ue4 

RUN	doxygen -v	# confirm doxygen version from docs-docker-base

RUN	git submodule set-branch --branch main documentation/docs-doxygen && \
	git submodule update --init documentation/docs-doxygen && \
	git tag

ADD	$CACHEBREAKER skipcache22

RUN	./documentation/build.sh && \
	eval "$(cat ./documentation/env.sh | grep "PROJECT_URL")" && \
	mkdir -p /var/www/html/$PROJECT_URL && \
	cp -r ./documentation/html/* /var/www/html/$PROJECT_URL

#ENTRYPOINT ["/docker-entrypoint.sh"]
#CMD	["nginx", "-g", "daemon off;"]

